Section "ServerFlags"
    Option "AutoAddDevices" "False"
EndSection

Section "InputDevice"
    Identifier "Keyboard0"
    Driver "evdev"
    Option "Device" "/dev/input/event3"  # Change this to match your device (ls -l /dev/input/by-id/)
    Option "XkbLayout" "us"
EndSection

Section "InputDevice"
    Identifier "Mouse0"
    Driver "evdev"
    Option "Device" "/dev/input/event3" # Change this to match your device
EndSection
